/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.luismendes.view;

import br.com.luismendes.controller.ControllerVenda;
import br.com.luismendes.view.update.TelaUpdateFornecedor;
import br.com.luismendes.view.update.TelaUpdateProduto;
import br.com.luismendes.view.update.TelaUpdateFuncionario;
import br.com.luismendes.view.update.TelaUpdateCliente;
import br.com.luismendes.view.update.TelaUpdateVenda;
import br.com.luismendes.view.novo.TelaNovoCliente;
import br.com.luismendes.view.novo.TelaNovoProduto;
import br.com.luismendes.view.novo.TelaNovoFuncionario;
import br.com.luismendes.view.novo.TelaNovoFornecedor;
import br.com.luismendes.view.novo.TelaNovaVenda;
import br.com.luismendes.model.dao.BDClientes;
import br.com.luismendes.model.dao.BDFornecedores;
import br.com.luismendes.model.dao.BDFuncionarios;
import br.com.luismendes.model.dao.BDItensVendidos;
import br.com.luismendes.model.dao.BDProdutos;
import br.com.luismendes.model.dao.BDVendas;
import br.com.luismendes.model.vo.ModelClientes;
import br.com.luismendes.model.vo.ModelVendas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author LuisWindows7
 */
public class TelaPrincipal extends javax.swing.JFrame {

    String NOME_FUNCIONARIO;
    String CPF_FUNCIONARIO;

    public TelaPrincipal() {
        this.CPF_FUNCIONARIO = "05020868159";
        this.NOME_FUNCIONARIO = "Luís Mendes Machado";

        initComponents();
        setLocationRelativeTo(null);

        //passar login funcionario para tela Nova Venda aqui
        BDVendas bdVendas = new BDVendas();
        bdVendas.preencheTabela("select * from vendas", jtVendas);

        BDClientes bdClientes = new BDClientes();
        bdClientes.preencheTabela("select * from clientes", jtClientes);

        BDProdutos bdProdutos = new BDProdutos();
        bdProdutos.preencheTabela("select * from produtos", jtProdutos);

        BDFuncionarios bdFuncionarios = new BDFuncionarios();
        bdFuncionarios.preencheTabela("select * from funcionarios", jtFuncionarios);

        BDFornecedores bdFornecedores = new BDFornecedores();
        bdFornecedores.preencheTabela("select * from fornecedores", jtFornecedores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFornecedores = new javax.swing.JTabbedPane();
        jpTelaVendas = new javax.swing.JPanel();
        jpBotoesVendas = new javax.swing.JPanel();
        jbNovaVenda = new javax.swing.JButton();
        jbEditarVenda = new javax.swing.JButton();
        jbExcluirVenda = new javax.swing.JButton();
        jtfBuscarCPFClienteVendas = new javax.swing.JTextField();
        jbBuscarCPFClienteVendas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVendas = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jpTelaClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        jpBotoesClientes = new javax.swing.JPanel();
        jbNovoCliente = new javax.swing.JButton();
        jbExcluirCliente = new javax.swing.JButton();
        jbEditarCliente = new javax.swing.JButton();
        jtfBuscarCPF = new javax.swing.JTextField();
        jbBuscarCPFCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jpTelaProdutos = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jbNovoProduto = new javax.swing.JButton();
        jbEditarProduto = new javax.swing.JButton();
        jbExcluirProduto = new javax.swing.JButton();
        jbBuscarProduto = new javax.swing.JButton();
        jtfBuscarProduto = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jpTelaFuncionarios = new javax.swing.JPanel();
        jpBotoesTelaFuncionarios = new javax.swing.JPanel();
        jbNovoFuncionario = new javax.swing.JButton();
        jbEditarFuncionario = new javax.swing.JButton();
        jbExcluirFuncionario = new javax.swing.JButton();
        jtfBuscarProduto1 = new javax.swing.JTextField();
        jbBuscarFuncionario = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtFuncionarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jpBotoesTelaFornecedores = new javax.swing.JPanel();
        jbNovoFornecedor = new javax.swing.JButton();
        jbEditarFornecedor = new javax.swing.JButton();
        jbExcluirFornecedor = new javax.swing.JButton();
        jtfBuscarFornecedores = new javax.swing.JTextField();
        jbBuscarFornecedores = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtFornecedores = new javax.swing.JTable();
        jpTelaAjuda = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MACHADO SOFTWARE");

        jpFornecedores.setToolTipText("");
        jpFornecedores.setName(""); // NOI18N
        jpFornecedores.setPreferredSize(new java.awt.Dimension(1366, 768));

        jbNovaVenda.setText("Nova");
        jbNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovaVendaActionPerformed(evt);
            }
        });

        jbEditarVenda.setText("Editar");
        jbEditarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarVendaActionPerformed(evt);
            }
        });

        jbExcluirVenda.setText("Excluir");
        jbExcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirVendaActionPerformed(evt);
            }
        });

        jbBuscarCPFClienteVendas.setText("Pesquisar Código");
        jbBuscarCPFClienteVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarCPFClienteVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesVendasLayout = new javax.swing.GroupLayout(jpBotoesVendas);
        jpBotoesVendas.setLayout(jpBotoesVendasLayout);
        jpBotoesVendasLayout.setHorizontalGroup(
            jpBotoesVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesVendasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jbNovaVenda)
                .addGap(18, 18, 18)
                .addComponent(jbEditarVenda)
                .addGap(18, 18, 18)
                .addComponent(jbExcluirVenda)
                .addGap(26, 26, 26)
                .addComponent(jtfBuscarCPFClienteVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscarCPFClienteVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBotoesVendasLayout.setVerticalGroup(
            jpBotoesVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesVendasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpBotoesVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpBotoesVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNovaVenda)
                        .addComponent(jbExcluirVenda)
                        .addComponent(jbEditarVenda))
                    .addGroup(jpBotoesVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfBuscarCPFClienteVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBuscarCPFClienteVendas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da venda", "Funcionário", "Cliente", "Preço total", "Data", "Hora"
            }
        ));
        jScrollPane2.setViewportView(jtVendas);

        javax.swing.GroupLayout jpTelaVendasLayout = new javax.swing.GroupLayout(jpTelaVendas);
        jpTelaVendas.setLayout(jpTelaVendasLayout);
        jpTelaVendasLayout.setHorizontalGroup(
            jpTelaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaVendasLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jpBotoesVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jpTelaVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jpTelaVendasLayout.setVerticalGroup(
            jpTelaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoesVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        jpFornecedores.addTab("Vendas", null, jpTelaVendas, "VENDAS");

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Endereço", "Telefone", "Loja de Referência 1", "Loja de Referência 2", "Situação"
            }
        ));
        jScrollPane1.setViewportView(jtClientes);

        jbNovoCliente.setText("Novo");
        jbNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoClienteActionPerformed(evt);
            }
        });

        jbExcluirCliente.setText("Excluir");
        jbExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirClienteActionPerformed(evt);
            }
        });

        jbEditarCliente.setText("Editar");
        jbEditarCliente.setMaximumSize(new java.awt.Dimension(50, 50));
        jbEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarClienteActionPerformed(evt);
            }
        });

        

        jbBuscarCPFCliente.setText("Pesquisar CPF");
        jbBuscarCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarCPFClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesClientesLayout = new javax.swing.GroupLayout(jpBotoesClientes);
        jpBotoesClientes.setLayout(jpBotoesClientesLayout);
        jpBotoesClientesLayout.setHorizontalGroup(
            jpBotoesClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesClientesLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jbNovoCliente)
                .addGap(41, 41, 41)
                .addComponent(jbEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jbExcluirCliente)
                .addGap(248, 248, 248)
                .addComponent(jtfBuscarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscarCPFCliente)
                .addGap(204, 204, 204))
        );
        jpBotoesClientesLayout.setVerticalGroup(
            jpBotoesClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jbEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbExcluirCliente)
                    .addComponent(jbNovoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfBuscarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarCPFCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpTelaClientesLayout = new javax.swing.GroupLayout(jpTelaClientes);
        jpTelaClientes.setLayout(jpTelaClientesLayout);
        jpTelaClientesLayout.setHorizontalGroup(
            jpTelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(jpBotoesClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jScrollPane1)
        );
        jpTelaClientesLayout.setVerticalGroup(
            jpTelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jpFornecedores.addTab("Clientes", null, jpTelaClientes, "CLIENTES");

        jbNovoProduto.setText("Novo");
        jbNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoProdutoActionPerformed(evt);
            }
        });

        jbEditarProduto.setText("Editar");
        jbEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarProdutoActionPerformed(evt);
            }
        });

        jbExcluirProduto.setText("Excluir");
        jbExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirProdutoActionPerformed(evt);
            }
        });

        jbBuscarProduto.setText("Pesquisar Código");

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CNPJ", "Preço", "Estoque"
            }
        ));
        jScrollPane5.setViewportView(jtProdutos);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jbNovoProduto)
                        .addGap(39, 39, 39)
                        .addComponent(jbEditarProduto)
                        .addGap(30, 30, 30)
                        .addComponent(jbExcluirProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBuscarProduto)
                        .addComponent(jtfBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNovoProduto)
                        .addComponent(jbExcluirProduto)
                        .addComponent(jbEditarProduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpTelaProdutosLayout = new javax.swing.GroupLayout(jpTelaProdutos);
        jpTelaProdutos.setLayout(jpTelaProdutosLayout);
        jpTelaProdutosLayout.setHorizontalGroup(
            jpTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTelaProdutosLayout.setVerticalGroup(
            jpTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaProdutosLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 429, Short.MAX_VALUE))
        );

        jpFornecedores.addTab("Produtos", null, jpTelaProdutos, "PRODUTOS");

        jbNovoFuncionario.setText("Novo");
        jbNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoFuncionarioActionPerformed(evt);
            }
        });

        jbEditarFuncionario.setText("Editar");
        jbEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarFuncionarioActionPerformed(evt);
            }
        });

        jbExcluirFuncionario.setText("Excluir");
        jbExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirFuncionarioActionPerformed(evt);
            }
        });

        jbBuscarFuncionario.setText("Pesquisar CPF");

        javax.swing.GroupLayout jpBotoesTelaFuncionariosLayout = new javax.swing.GroupLayout(jpBotoesTelaFuncionarios);
        jpBotoesTelaFuncionarios.setLayout(jpBotoesTelaFuncionariosLayout);
        jpBotoesTelaFuncionariosLayout.setHorizontalGroup(
            jpBotoesTelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesTelaFuncionariosLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jbNovoFuncionario)
                .addGap(35, 35, 35)
                .addComponent(jbEditarFuncionario)
                .addGap(34, 34, 34)
                .addComponent(jbExcluirFuncionario)
                .addContainerGap(770, Short.MAX_VALUE))
            .addGroup(jpBotoesTelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpBotoesTelaFuncionariosLayout.createSequentialGroup()
                    .addGap(444, 444, 444)
                    .addComponent(jtfBuscarProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jbBuscarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
        );
        jpBotoesTelaFuncionariosLayout.setVerticalGroup(
            jpBotoesTelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesTelaFuncionariosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpBotoesTelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovoFuncionario)
                    .addComponent(jbExcluirFuncionario)
                    .addComponent(jbEditarFuncionario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpBotoesTelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpBotoesTelaFuncionariosLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jpBotoesTelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBuscarFuncionario)
                        .addComponent(jtfBuscarProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        jtFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Endereço", "Telefone"
            }
        ));
        jScrollPane6.setViewportView(jtFuncionarios);

        javax.swing.GroupLayout jpTelaFuncionariosLayout = new javax.swing.GroupLayout(jpTelaFuncionarios);
        jpTelaFuncionarios.setLayout(jpTelaFuncionariosLayout);
        jpTelaFuncionariosLayout.setHorizontalGroup(
            jpTelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTelaFuncionariosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE))
                    .addComponent(jpBotoesTelaFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpTelaFuncionariosLayout.setVerticalGroup(
            jpTelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaFuncionariosLayout.createSequentialGroup()
                .addComponent(jpBotoesTelaFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        jpFornecedores.addTab("Funcionários", null, jpTelaFuncionarios, "FUNCIONÁRIOS");

        jbNovoFornecedor.setText("Novo");
        jbNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoFornecedorActionPerformed(evt);
            }
        });

        jbEditarFornecedor.setText("Editar");
        jbEditarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarFornecedorActionPerformed(evt);
            }
        });

        jbExcluirFornecedor.setText("Excluir");
        jbExcluirFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirFornecedorActionPerformed(evt);
            }
        });

        jbBuscarFornecedores.setText("Pesquisar CNPJ");
        jbBuscarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarFornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesTelaFornecedoresLayout = new javax.swing.GroupLayout(jpBotoesTelaFornecedores);
        jpBotoesTelaFornecedores.setLayout(jpBotoesTelaFornecedoresLayout);
        jpBotoesTelaFornecedoresLayout.setHorizontalGroup(
            jpBotoesTelaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesTelaFornecedoresLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jbNovoFornecedor)
                .addGap(27, 27, 27)
                .addComponent(jbEditarFornecedor)
                .addGap(42, 42, 42)
                .addComponent(jbExcluirFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                .addComponent(jtfBuscarFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscarFornecedores)
                .addGap(65, 65, 65))
        );
        jpBotoesTelaFornecedoresLayout.setVerticalGroup(
            jpBotoesTelaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesTelaFornecedoresLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpBotoesTelaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBotoesTelaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBuscarFornecedores)
                        .addComponent(jtfBuscarFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBotoesTelaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNovoFornecedor)
                        .addComponent(jbExcluirFornecedor)
                        .addComponent(jbEditarFornecedor)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jtFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CNPJ", "Nome", "Endereço", "Telefone"
            }
        ));
        jScrollPane3.setViewportView(jtFornecedores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jpBotoesTelaFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jpBotoesTelaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jpFornecedores.addTab("Fornecedores", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Protótipo de Software de Papelaria Desktop");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Tudo começou como um trabalho para a disciplina de Programação Orientada a Objetos \nII na faculdade de Análise e Desenvolvimento de Sistemas e hoje lhes trago esse \nprotótipo de um sistema de controle de Vendas, Funcionários,Clientes, Fornecedores \ne Produtos de uma papelaria. Após algumas entrevistas e conversas com funcionários \nda Papelaria do Câmpus e com professores chegou-se ao presente resultado.\n\nEsse material consiste de:\n\tum .jar, \n\tuma pasta de códigos do Netbeans 8.0.2\n\te o do banco de dados bd_papelaria.sql\n\nFerramentas utilizadas: XAMPP 3.2.1,Netbeans 8.0.2 + Java 8, Driver JDBC e Windows 7\n\nFiquem a vontade para modificar o código e melhorá-lo!\n\nemail: luis.mendes070@gmail.com\n");
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(276, 276, 276))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpTelaAjudaLayout = new javax.swing.GroupLayout(jpTelaAjuda);
        jpTelaAjuda.setLayout(jpTelaAjudaLayout);
        jpTelaAjudaLayout.setHorizontalGroup(
            jpTelaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1137, Short.MAX_VALUE)
            .addGroup(jpTelaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpTelaAjudaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpTelaAjudaLayout.setVerticalGroup(
            jpTelaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(jpTelaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpTelaAjudaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(320, Short.MAX_VALUE)))
        );

        jpFornecedores.addTab("Sobre", null, jpTelaAjuda, "AJUDA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 671, Short.MAX_VALUE))
        );


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarCPFClienteActionPerformed

        BDClientes bdClientes = new BDClientes();

        ModelClientes cliente = bdClientes.buscar(jtfBuscarCPF.getText());

        if (cliente != null) {

            TelaUpdateCliente tuc = new TelaUpdateCliente(cliente);

        }
    }//GEN-LAST:event_jbBuscarCPFClienteActionPerformed

    private void jbEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarClienteActionPerformed
        // TODO add your handling code here:
        if (jtClientes.getSelectedRow() > -1) {

            //preencherTelaUpdateCliente
            TelaUpdateCliente telaUpdateCliente = new TelaUpdateCliente(jtClientes);
            telaUpdateCliente.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }
    }//GEN-LAST:event_jbEditarClienteActionPerformed

    private void jbExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirClienteActionPerformed

        int linha = jtClientes.getSelectedRow();

        if (linha > -1) {

            String nome = jtClientes.getModel().getValueAt(linha, 1).toString();
            String cpf = jtClientes.getModel().getValueAt(linha, 0).toString();

            int resposta = JOptionPane.showConfirmDialog(null,
                    "\nNome = " + nome
                    + "\nCPF = " + cpf,
                    "Excluir cliente", JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {

                BDClientes bdClientes = new BDClientes();

                bdClientes.excluir("clientes", "cpf_cliente", cpf);
                bdClientes.preencheTabela("select * from clientes", jtClientes);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da Tabela Clientes!");
        }
    }//GEN-LAST:event_jbExcluirClienteActionPerformed

    private void jbNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoClienteActionPerformed

        TelaNovoCliente telaNovoCliente = new TelaNovoCliente(jtClientes, jbEditarCliente, jbExcluirCliente, jbBuscarCPFCliente);

    }//GEN-LAST:event_jbNovoClienteActionPerformed

    private void jbNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovaVendaActionPerformed

        jbEditarVenda.setEnabled(false);
        jbExcluirVenda.setEnabled(false);
        jtfBuscarCPFClienteVendas.setEnabled(false);
        jbBuscarCPFClienteVendas.setEnabled(false);

        TelaNovaVenda telaNovaVenda = new TelaNovaVenda(CPF_FUNCIONARIO, NOME_FUNCIONARIO, jtVendas, jtClientes, jtProdutos);
        telaNovaVenda.setVisible(true);

        jbEditarVenda.setEnabled(true);
        jbExcluirVenda.setEnabled(true);
        jtfBuscarCPFClienteVendas.setEnabled(true);
        jbBuscarCPFClienteVendas.setEnabled(true);

    }//GEN-LAST:event_jbNovaVendaActionPerformed

    private void jbBuscarCPFClienteVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarCPFClienteVendasActionPerformed


    }//GEN-LAST:event_jbBuscarCPFClienteVendasActionPerformed

    private void jbNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoProdutoActionPerformed
        // TODO add your handling code here:
        jbEditarProduto.setEnabled(false);
        jbExcluirProduto.setEnabled(false);
        jbBuscarProduto.setEnabled(false);

        TelaNovoProduto telaNovoProduto = new TelaNovoProduto(jtProdutos);

        jbEditarProduto.setEnabled(true);
        jbExcluirProduto.setEnabled(true);
        jbBuscarProduto.setEnabled(true);
    }//GEN-LAST:event_jbNovoProdutoActionPerformed

    private void jbNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoFuncionarioActionPerformed
        // TODO add your handling code here:
        jbEditarFuncionario.setEnabled(false);
        jbExcluirFuncionario.setEnabled(false);
        jbBuscarFuncionario.setEnabled(false);

        TelaNovoFuncionario telaNovoFuncionario = new TelaNovoFuncionario(jtFuncionarios);
        telaNovoFuncionario.setVisible(true);

        jbEditarFuncionario.setEnabled(true);
        jbExcluirFuncionario.setEnabled(true);
        jbBuscarFuncionario.setEnabled(true);

    }//GEN-LAST:event_jbNovoFuncionarioActionPerformed

    private void jbEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarFuncionarioActionPerformed
        // TODO add your handling code here:
        if (jtFuncionarios.getSelectedRow() > -1) {

            //preencherTelaUpdate
            TelaUpdateFuncionario telaUpdateFuncionario = new TelaUpdateFuncionario(jtFuncionarios);

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }
    }//GEN-LAST:event_jbEditarFuncionarioActionPerformed

    private void jbExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirFuncionarioActionPerformed

        int linha = jtFuncionarios.getSelectedRow();

        if (linha > -1) {

            String nome = jtFuncionarios.getModel().getValueAt(linha, 1).toString();

            String cpf = jtFuncionarios.getModel().getValueAt(linha, 0).toString();

            int resposta = JOptionPane.showConfirmDialog(null,
                    "Nome: " + nome
                    + "\nCPF:" + cpf,
                    "Excluir funcionário ",
                    JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {
                BDFuncionarios bdFuncionarios = new BDFuncionarios();
                bdFuncionarios.excluir("funcionarios", "cpf_funcionario", cpf);
                bdFuncionarios.preencheTabela("select * from funcionarios", jtFuncionarios);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }

    }//GEN-LAST:event_jbExcluirFuncionarioActionPerformed

    private void jbExcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirVendaActionPerformed
        
        int linha = jtVendas.getSelectedRow();

        if (linha > -1) {

            int idVenda = Integer.parseInt(jtVendas.getModel().getValueAt(linha, 0).toString());

            BDVendas bdv = new BDVendas();
            ModelVendas mv = bdv.buscarVenda(idVenda);

            if (mv != null) {

                String cpf = mv.getCpfCliente();

                BDClientes bdc = new BDClientes();
                ModelClientes mc = bdc.buscar(cpf);

                if (mc != null) {
                    String nome = mc.getNome();

                    int resposta = JOptionPane.showConfirmDialog(null, ""
                            + "\n Código de Venda: " + idVenda
                            + "\n Cliente: " + nome,
                            "Excluir venda",
                            JOptionPane.YES_NO_OPTION);

                    if (resposta == JOptionPane.YES_OPTION) {

                        ControllerVenda controllerVenda = new ControllerVenda();
                        controllerVenda.cancelaVendas(mv);

                        BDVendas bdVendas = new BDVendas();
                        bdVendas.preencheTabela("select * from vendas", jtVendas);
                    }
                }
            }//fim if 
        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }
        BDVendas bdVendas = new BDVendas();
        bdVendas.preencheTabela("select * from vendas", jtVendas);
    }//GEN-LAST:event_jbExcluirVendaActionPerformed

    private void jbExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirProdutoActionPerformed
        // TODO add your handling code here:
        int linha = jtProdutos.getSelectedRow();

        if (linha > -1) {

            String nome = jtProdutos.getModel().getValueAt(linha, 1).toString();

            String idProduto = jtProdutos.getModel().getValueAt(linha, 0).toString();

            int resposta = JOptionPane.showConfirmDialog(null, "Nome: " + nome + "\nCódigo:" + idProduto, "Excluir produto", JOptionPane.OK_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {
                BDProdutos bdProdutos = new BDProdutos();
                bdProdutos.excluir("produtos", "id_produto", idProduto);
                bdProdutos.preencheTabela("select * from produtos", jtProdutos);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da Tabela Clientes!");
        }
    }//GEN-LAST:event_jbExcluirProdutoActionPerformed

    private void jbExcluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirFornecedorActionPerformed
        // TODO add your handling code here:

        int linha = jtFornecedores.getSelectedRow();

        if (linha > -1) {

            String nome = jtFornecedores.getModel().getValueAt(linha, 1).toString();

            String cnpj = jtFornecedores.getModel().getValueAt(linha, 0).toString();

            int resposta = JOptionPane.showConfirmDialog(null, "Excluir fornecedor " + nome + "?");

            if (resposta == JOptionPane.YES_OPTION) {
                BDFornecedores bdFornecedores = new BDFornecedores();
                bdFornecedores.excluir("fornecedores", "cnpj", cnpj);
                bdFornecedores.preencheTabela("select * from fornecedores", jtFornecedores);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }


    }//GEN-LAST:event_jbExcluirFornecedorActionPerformed

    private void jbEditarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarFornecedorActionPerformed
        // TODO add your handling code here:
        if (jtFornecedores.getSelectedRow() > -1) {

            //preencherTelaUpdateCliente
            TelaUpdateFornecedor telaUpdateFornecedor = new TelaUpdateFornecedor(jtFornecedores);

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }
    }//GEN-LAST:event_jbEditarFornecedorActionPerformed

    private void jbEditarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarVendaActionPerformed

        if (jtVendas.getSelectedRow() > -1) {

            try {

                int idVenda = (int) jtVendas.getValueAt(jtVendas.getSelectedRow(), 0);

                BDVendas bdv = new BDVendas();
                ModelVendas venda = bdv.buscarVenda(idVenda);

                if (venda != null) {

                    //QUANDO UMA VENDA É ATUALIZADA,
                    //O CPF DO USUÁRIO É ATUALIZADO PARA O CPF DO FUNCIONÁRIO QUE FIZER A ATUALIZAÇÃO
                    venda.setCpfFuncionario(CPF_FUNCIONARIO);

                    jbNovaVenda.setEnabled(false);
                    jbExcluirVenda.setEnabled(false);
                    jbBuscarCPFClienteVendas.setEnabled(false);

                    TelaUpdateVenda telaUpdateVenda
                            = new TelaUpdateVenda(venda, jtVendas, jtClientes,
                                    jtProdutos, jbNovaVenda, jbExcluirVenda,
                                    jbBuscarCPFClienteVendas);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao recuperar código de venda da tabela vendas!\n" + e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }
    }//GEN-LAST:event_jbEditarVendaActionPerformed

    private void jbEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarProdutoActionPerformed
        // TODO add your handling code here:
        if (jtProdutos.getSelectedRow() > -1) {

            //preencherTelaUpdateProduto
            TelaUpdateProduto telaUpdateProduto = new TelaUpdateProduto(jtProdutos);

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }
    }//GEN-LAST:event_jbEditarProdutoActionPerformed

    private void jbNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoFornecedorActionPerformed
        // TODO add your handling code here:
        jbEditarFornecedor.setEnabled(false);
        jbExcluirFornecedor.setEnabled(false);
        jbBuscarFornecedores.setEnabled(false);

        TelaNovoFornecedor telaNovoCliente = new TelaNovoFornecedor(jtFornecedores);

        jbEditarFornecedor.setEnabled(true);
        jbExcluirFornecedor.setEnabled(true);
        jbBuscarFornecedores.setEnabled(true);
    }//GEN-LAST:event_jbNovoFornecedorActionPerformed

    private void jbBuscarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarFornecedoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbBuscarCPFCliente;
    private javax.swing.JButton jbBuscarCPFClienteVendas;
    private javax.swing.JButton jbBuscarFornecedores;
    private javax.swing.JButton jbBuscarFuncionario;
    private javax.swing.JButton jbBuscarProduto;
    private javax.swing.JButton jbEditarCliente;
    private javax.swing.JButton jbEditarFornecedor;
    private javax.swing.JButton jbEditarFuncionario;
    private javax.swing.JButton jbEditarProduto;
    private javax.swing.JButton jbEditarVenda;
    private javax.swing.JButton jbExcluirCliente;
    private javax.swing.JButton jbExcluirFornecedor;
    private javax.swing.JButton jbExcluirFuncionario;
    private javax.swing.JButton jbExcluirProduto;
    private javax.swing.JButton jbExcluirVenda;
    private javax.swing.JButton jbNovaVenda;
    private javax.swing.JButton jbNovoCliente;
    private javax.swing.JButton jbNovoFornecedor;
    private javax.swing.JButton jbNovoFuncionario;
    private javax.swing.JButton jbNovoProduto;
    private javax.swing.JPanel jpBotoesClientes;
    private javax.swing.JPanel jpBotoesTelaFornecedores;
    private javax.swing.JPanel jpBotoesTelaFuncionarios;
    private javax.swing.JPanel jpBotoesVendas;
    private javax.swing.JTabbedPane jpFornecedores;
    private javax.swing.JPanel jpTelaAjuda;
    private javax.swing.JPanel jpTelaClientes;
    private javax.swing.JPanel jpTelaFuncionarios;
    private javax.swing.JPanel jpTelaProdutos;
    private javax.swing.JPanel jpTelaVendas;
    private javax.swing.JTable jtClientes;
    private javax.swing.JTable jtFornecedores;
    private javax.swing.JTable jtFuncionarios;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JTable jtVendas;
    private javax.swing.JTextField jtfBuscarCPF;
    private javax.swing.JTextField jtfBuscarCPFClienteVendas;
    private javax.swing.JTextField jtfBuscarFornecedores;
    private javax.swing.JTextField jtfBuscarProduto;
    private javax.swing.JTextField jtfBuscarProduto1;
    // End of variables declaration//GEN-END:variables

}
