/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.luismendes.view.novo;

import br.com.luismendes.controller.ControllerItemVenda;
import br.com.luismendes.controller.ControllerVenda;
import br.com.luismendes.model.dao.BDClientes;
import br.com.luismendes.model.dao.BDItensVendidos;
import br.com.luismendes.model.dao.BDVendas;
import br.com.luismendes.model.vo.ModelClientes;
import br.com.luismendes.model.vo.ModelItensVendidos;
import br.com.luismendes.model.vo.ModelVendas;
import br.com.luismendes.view.update.TelaUpdateItem;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author LuisWindows7
 */
public class TelaNovaVenda extends javax.swing.JFrame {

    private ArrayList<ModelItensVendidos> listaCompras;
    private ModelVendas vendas;
    private JTable jtClientes;
    private JTable jtProdutos;
    private JTable jtVendas;

    String NOME_FUNCIONARIO;
    String CPF_FUNCIONARIO;

    /**
     * Creates new form TelaNovaVenda
     *
     * @param cpfFuncionario
     * @param jtVendas
     */
    public TelaNovaVenda(String CPF_FUNCIONARIO, String NOME_FUNCIONARIO,
            JTable jtVendas, JTable jtClientes, JTable jtProdutos) {

        this.CPF_FUNCIONARIO = CPF_FUNCIONARIO;
        this.NOME_FUNCIONARIO = NOME_FUNCIONARIO;

        this.jtVendas = jtVendas;
        this.jtClientes = jtClientes;
        this.jtProdutos = jtProdutos;

        initComponents();
        setLocationRelativeTo(null);

        String s = jlNomeFuncionario.getText();
        jlNomeFuncionario.setText(s + NOME_FUNCIONARIO);

        vendas = new ModelVendas();

    }//fim do construtor TelaNovaVenda

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlNomeFuncionario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfPrecoTotal = new javax.swing.JTextField();
        jtfCpfClienteNovaVenda = new javax.swing.JTextField();
        jbNovoItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtItensVenda = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jbContinuarVenda = new javax.swing.JButton();
        jbEditarItem = new javax.swing.JButton();
        jbExcluirItem = new javax.swing.JButton();
        jlNomeCliente = new javax.swing.JLabel();
        jbSairNovaVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Venda");
        setResizable(false);

        jlNomeFuncionario.setText("Nome do funcionário: ");

        jLabel2.setText("CPF Cliente");

        jtfPrecoTotal.setEditable(false);

        jbNovoItem.setText("Novo item");
        jbNovoItem.setEnabled(false);
        jbNovoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoItemActionPerformed(evt);
            }
        });

        jtItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código do item", "Código da venda", "Código do produto", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jtItensVenda);

        jLabel3.setText("Preço total");

        jbContinuarVenda.setText("Continuar Venda");
        jbContinuarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbContinuarVendaActionPerformed(evt);
            }
        });

        jbEditarItem.setText("Editar item");
        jbEditarItem.setEnabled(false);
        jbEditarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarItemActionPerformed(evt);
            }
        });

        jbExcluirItem.setText("Excluir item");
        jbExcluirItem.setEnabled(false);
        jbExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirItemActionPerformed(evt);
            }
        });

        jlNomeCliente.setText("Nome do cliente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCpfClienteNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbContinuarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jbNovoItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbEditarItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbExcluirItem))
                            .addComponent(jlNomeFuncionario)
                            .addComponent(jlNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNomeFuncionario)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfCpfClienteNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbContinuarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addComponent(jlNomeCliente)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovoItem)
                    .addComponent(jbEditarItem)
                    .addComponent(jbExcluirItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jbSairNovaVenda.setText("Sair");
        jbSairNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairNovaVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSairNovaVenda)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSairNovaVenda)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoItemActionPerformed

        TelaNovoItem telaNovoItem;

        telaNovoItem = new TelaNovoItem(listaCompras, jtItensVenda, vendas, jtfPrecoTotal, jtProdutos);
    }//GEN-LAST:event_jbNovoItemActionPerformed

    private void jbContinuarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbContinuarVendaActionPerformed
        BDClientes bdc = new BDClientes();

        jlNomeCliente.setText("");

        ModelClientes mc = bdc.buscar(jtfCpfClienteNovaVenda.getText());

        if (mc != null) {
            jlNomeCliente.setText("Olá, " + mc.getNome());

            vendas.setCpfCliente(mc.getCpf());
            vendas.setCpfFuncionario(CPF_FUNCIONARIO);

            //BD cria id_venda
            BDVendas bdv = new BDVendas();
            bdv.inserirVenda(vendas);
            bdv.preencheTabela("select * from vendas", jtVendas);

            int ultimaLinha = jtVendas.getRowCount() - 1;

            String stringIdVenda = jtVendas.getValueAt(ultimaLinha, 0).toString();

            vendas = bdv.buscarVenda(Integer.parseInt(stringIdVenda));

            if (vendas != null) {
                //JOptionPane.showMessageDialog(null, "Buscou id_venda usando data_venda!\n id_venda" + vendas.getIdVenda());

                jbNovoItem.setEnabled(true);
                jbEditarItem.setEnabled(true);
                jbExcluirItem.setEnabled(true);
            }

        } else {

            int resposta = JOptionPane.showConfirmDialog(null, "Cadastrar novo cliente?");

            if (resposta == JOptionPane.YES_OPTION) {
                TelaNovoCliente telaNovoCliente = new TelaNovoCliente(jtClientes, jbNovoItem, jbEditarItem, jbExcluirItem);
            }
        }
    }//GEN-LAST:event_jbContinuarVendaActionPerformed

    private void jbSairNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairNovaVendaActionPerformed

        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que quer sair?", "Sair", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            resposta = JOptionPane.showConfirmDialog(null, "Salvar venda ao sair?", "Salvar", JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {

                //grava venda no bd e atualiza tabela de vendas para usuário do sistema
                BDVendas bdVenda = new BDVendas();
                bdVenda.atualizar(vendas);
                bdVenda.preencheTabela("select * from vendas", jtVendas);

                jbNovoItem.setEnabled(false);

                dispose();

            } else if (resposta == JOptionPane.NO_OPTION) {//apaga venda

                ControllerVenda controllerVenda = new ControllerVenda();
                controllerVenda.cancelaVendas(vendas);

                //Atualiza tabela de vendas para usuário do sistema
                BDVendas bdVenda = new BDVendas();
                bdVenda.preencheTabela("select * from vendas", jtVendas);
            }
            dispose();
        }
    }//GEN-LAST:event_jbSairNovaVendaActionPerformed

    private void jbEditarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarItemActionPerformed

        int linha;

        linha = jtItensVenda.getSelectedRow();

        if (linha > -1) {

            int idVenda = vendas.getIdVenda();
            int idProduto = (int) jtItensVenda.getValueAt(linha, 2);
            int qtdItens = (int) jtItensVenda.getValueAt(linha, 3);

            ModelItensVendidos modelItensVendido = new ModelItensVendidos(idVenda, idProduto, qtdItens);

            TelaUpdateItem telaUpdateItem;

            telaUpdateItem = new TelaUpdateItem(modelItensVendido,
                    jtItensVenda, jtProdutos, vendas, jtfPrecoTotal, listaCompras);

            jtfPrecoTotal.setText("" + vendas.getPrecoTotal());

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }

    }//GEN-LAST:event_jbEditarItemActionPerformed

    private void jbExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirItemActionPerformed

        ControllerItemVenda controllerItemVenda = new ControllerItemVenda();
        controllerItemVenda.excluir(jtItensVenda, listaCompras, vendas);

        jtfPrecoTotal.setText("" + vendas.getPrecoTotal());
    }//GEN-LAST:event_jbExcluirItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbContinuarVenda;
    private javax.swing.JButton jbEditarItem;
    private javax.swing.JButton jbExcluirItem;
    private javax.swing.JButton jbNovoItem;
    private javax.swing.JButton jbSairNovaVenda;
    private javax.swing.JLabel jlNomeCliente;
    private javax.swing.JLabel jlNomeFuncionario;
    private javax.swing.JTable jtItensVenda;
    private javax.swing.JTextField jtfCpfClienteNovaVenda;
    private javax.swing.JTextField jtfPrecoTotal;
    // End of variables declaration//GEN-END:variables

}
