/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.luismendes.view.update;

import br.com.luismendes.controller.ControllerItemVenda;
import br.com.luismendes.controller.ControllerVenda;
import br.com.luismendes.model.dao.BDClientes;
import br.com.luismendes.model.dao.BDFuncionarios;
import br.com.luismendes.model.dao.BDItensVendidos;
import br.com.luismendes.model.dao.BDProdutos;
import br.com.luismendes.model.dao.BDVendas;
import br.com.luismendes.model.vo.ModelClientes;
import br.com.luismendes.model.vo.ModelFuncionarios;
import br.com.luismendes.model.vo.ModelItensVendidos;
import br.com.luismendes.model.vo.ModelVendas;
import br.com.luismendes.view.novo.TelaNovoCliente;
import br.com.luismendes.view.novo.TelaNovoItem;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author LuisWindows7
 */
public class TelaUpdateVenda extends javax.swing.JFrame {

    String CPF_FUNCIONARIO;
    String NOME_FUNCIONARIO;

    ModelVendas venda = null;
    int linhaSelecionada;

    JTable jtVendas = null;
    JTable jtClientes = null;
    JTable jtProdutos = null;

    ArrayList dados = new ArrayList();
    ArrayList<ModelItensVendidos> listaCompras = new ArrayList<>();

    JButton jbNovaVenda;
    JButton jbExcluirVenda;
    JButton jbBuscarCPFClienteVendas;

    /**
     * Creates new form TelaUpdateVendas
     */
    public TelaUpdateVenda(
            ModelVendas venda,
            JTable jtVendas,
            JTable jtClientes,
            JTable jtProdutos, JButton jbNovaVenda, JButton jbExcluirVenda, JButton jbBuscarCPFClienteVendas) {

        this.venda = venda;
        this.CPF_FUNCIONARIO = venda.getCpfFuncionario();

        BDFuncionarios bdf = new BDFuncionarios();
        ModelFuncionarios mf = bdf.buscar(CPF_FUNCIONARIO);
        this.NOME_FUNCIONARIO = mf.getNome();

        this.jtVendas = jtVendas;
        this.jtClientes = jtClientes;
        this.jtProdutos = jtProdutos;
        this.jbNovaVenda = jbNovaVenda;
        this.jbExcluirVenda = jbExcluirVenda;
        this.jbBuscarCPFClienteVendas = jbBuscarCPFClienteVendas;

        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);

        jtfNomeFuncionario.setText(NOME_FUNCIONARIO);

        linhaSelecionada = jtVendas.getSelectedRow();

        if (venda != null) {
            //preenche campos que serão editados pelo funcionário
            jtfNomeFuncionario.setText(jtVendas.getValueAt(linhaSelecionada, 1).toString());
            jtfCpfClienteNovaVenda.setText(venda.getCpfCliente());
            //atualiza tabela de itens que estão sendo vendidos
            BDItensVendidos vendidos = new BDItensVendidos();
            vendidos.exibeTabelaItensCompleta("select * from itens_vendidos where id_venda = " + venda.getIdVenda(), jtItensVenda);

            //Diz olá
            BDClientes bdc = new BDClientes();
            ModelClientes cliente = bdc.buscar(jtfCpfClienteNovaVenda.getText());

            if (cliente != null) {
                jlOlaCliente.setText("Olá, " + cliente.getNome());

                jtfPrecoTotal.setText("" + venda.getPrecoTotal());

                jbNovoItem.setEnabled(true);
                jbEditarItem.setEnabled(true);
                jbExcluirItem.setEnabled(true);

                jbNovaVenda.setEnabled(true);
                jbExcluirVenda.setEnabled(true);
                jbBuscarCPFClienteVendas.setEnabled(true);

            }
        }//fim if
    }//fim do construtor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSairNovaVenda = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNomeFuncionario = new javax.swing.JTextField();
        jtfPrecoTotal = new javax.swing.JTextField();
        jtfCpfClienteNovaVenda = new javax.swing.JTextField();
        jbEditarItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtItensVenda = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jlOlaCliente = new javax.swing.JLabel();
        jbNovoItem = new javax.swing.JButton();
        jbExcluirItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar venda");
        setResizable(false);

        jbSairNovaVenda.setText("Sair");
        jbSairNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairNovaVendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Funcionário");

        jLabel2.setText("CPF Cliente");

        jtfNomeFuncionario.setEditable(false);
        jtfNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeFuncionarioActionPerformed(evt);
            }
        });

        jtfPrecoTotal.setEditable(false);

        jtfCpfClienteNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCpfClienteNovaVendaActionPerformed(evt);
            }
        });

        jbEditarItem.setText("Editar item");
        jbEditarItem.setEnabled(false);
        jbEditarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarItemActionPerformed(evt);
            }
        });

        jtItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código do item", "Código da venda", "Código do produto", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jtItensVenda);

        jLabel3.setText("Preço total");

        jbNovoItem.setText("Novo item");
        jbNovoItem.setEnabled(false);
        jbNovoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoItemActionPerformed(evt);
            }
        });

        jbExcluirItem.setText("Excluir item");
        jbExcluirItem.setEnabled(false);
        jbExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfCpfClienteNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jlOlaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfNomeFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(395, 395, 395)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jbNovoItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbEditarItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluirItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpfClienteNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOlaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditarItem)
                    .addComponent(jbExcluirItem)
                    .addComponent(jbNovoItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSairNovaVenda)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSairNovaVenda)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairNovaVendaActionPerformed

        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que quer sair?", "Sair", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            resposta = JOptionPane.showConfirmDialog(null, "Salvar alterações na venda ao sair?", "Salvar", JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {

                try {

                    //grava venda no bd e atualiza tabela de vendas para usuário do sistema
                    BDVendas bdVenda = new BDVendas();
                    bdVenda.atualizar(venda);
                    bdVenda.preencheTabela("select * from vendas", jtVendas);
                    jbNovoItem.setEnabled(false);
                    dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao salvar venda!");
                }
            } else if (resposta == JOptionPane.NO_OPTION) {

                ControllerVenda controllerVenda = new ControllerVenda();
                controllerVenda.cancelaVendas(venda);

                //Atualiza tabela de vendas para usuário do sistema
                BDVendas bdVenda = new BDVendas();
                bdVenda.preencheTabela("select * from vendas", jtVendas);

            }
            dispose();
        }
    }//GEN-LAST:event_jbSairNovaVendaActionPerformed

    private void jtfNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeFuncionarioActionPerformed

    private void jtfCpfClienteNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCpfClienteNovaVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCpfClienteNovaVendaActionPerformed

    private void jbEditarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarItemActionPerformed
        
        int linha;

        linha = jtItensVenda.getSelectedRow();

        if (linha > -1) {

            int idItemVendido = (int) jtItensVenda.getValueAt(linha, 0);
            int idVenda = venda.getIdVenda();
            int idProduto = (int) jtItensVenda.getValueAt(linha, 2);
            int qtdItens = (int) jtItensVenda.getValueAt(linha, 3);

            ModelItensVendidos itemAntesEditar = 
                    new ModelItensVendidos(idItemVendido, idVenda, idProduto, qtdItens);

            TelaUpdateItem telaUpdateItem = 
                    new TelaUpdateItem( itemAntesEditar,jtItensVenda, jtProdutos, venda, jtfPrecoTotal, listaCompras);

            jtfPrecoTotal.setText("" + venda.getPrecoTotal());

        } else {
            JOptionPane.showMessageDialog(null, "Você deve escolher uma linha da tabela!");
        }
    }//GEN-LAST:event_jbEditarItemActionPerformed

    private void jbNovoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoItemActionPerformed

        TelaNovoItem telaNovoItem = new TelaNovoItem(listaCompras, jtItensVenda, venda, jtfPrecoTotal, jtProdutos);

    }//GEN-LAST:event_jbNovoItemActionPerformed

    private void jbExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirItemActionPerformed

        ControllerItemVenda controllerItemVenda = new ControllerItemVenda();
        controllerItemVenda.excluir(jtItensVenda, listaCompras, venda);

        jtfPrecoTotal.setText("" + venda.getPrecoTotal());
        BDProdutos bdp = new BDProdutos();
        bdp.preencheTabela("select * from produtos", jtProdutos);
    }//GEN-LAST:event_jbExcluirItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditarItem;
    private javax.swing.JButton jbExcluirItem;
    private javax.swing.JButton jbNovoItem;
    private javax.swing.JButton jbSairNovaVenda;
    private javax.swing.JLabel jlOlaCliente;
    private javax.swing.JTable jtItensVenda;
    private javax.swing.JTextField jtfCpfClienteNovaVenda;
    private javax.swing.JTextField jtfNomeFuncionario;
    private javax.swing.JTextField jtfPrecoTotal;
    // End of variables declaration//GEN-END:variables
}
