/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.luismendes.view.update;

import br.com.luismendes.controller.ControllerItemVenda;
import br.com.luismendes.model.dao.BDItensVendidos;
import br.com.luismendes.model.dao.BDProdutos;
import br.com.luismendes.model.vo.ModelItensVendidos;
import br.com.luismendes.model.vo.ModelProdutos;
import br.com.luismendes.model.vo.ModelVendas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author LuisWindows7
 */
public class TelaUpdateItem extends javax.swing.JFrame {

    JTable jtItensVenda;
    ModelItensVendidos itemEditando;
    JTable jtProdutos;
    int linhaSelecionada;
    ModelVendas venda;
    JTextField jtfPrecoTotal;
    ArrayList<ModelItensVendidos> listaCompras;

    public TelaUpdateItem(
            ModelItensVendidos modelItensVendido, JTable jtItensVenda,
            JTable jtProdutos, ModelVendas venda, JTextField jtfPrecoTotal, ArrayList<ModelItensVendidos> listaCompras) {

        this.itemEditando = modelItensVendido;
        this.jtItensVenda = jtItensVenda;
        this.jtProdutos = jtProdutos;

        this.venda = venda;
        this.jtfPrecoTotal = jtfPrecoTotal;
        this.listaCompras = listaCompras;

        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);

        linhaSelecionada = jtItensVenda.getSelectedRow();

        jtfIdItem.setText("" + modelItensVendido.getIdProduto());
        jtfQuantidadeItem.setText("" + modelItensVendido.getQuantidadeItens());

    }//FIM DO CONSTRUTOR

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfIdItem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfQuantidadeItem = new javax.swing.JTextField();
        jbUpdateItem = new javax.swing.JButton();
        jbCancelAddItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar item");
        setResizable(false);

        jLabel1.setText("Código Item");

        jtfIdItem.setEnabled(false);

        jLabel2.setText("Quantidade");

        jbUpdateItem.setText("Salvar");
        jbUpdateItem.setToolTipText("Adicionar a lista de compras");
        jbUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateItemActionPerformed(evt);
            }
        });

        jbCancelAddItem.setText("Cancelar ");
        jbCancelAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelAddItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbUpdateItem)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfQuantidadeItem)
                            .addComponent(jtfIdItem))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbCancelAddItem)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfQuantidadeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelAddItem)
                    .addComponent(jbUpdateItem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbUpdateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateItemActionPerformed

        ControllerItemVenda controllerItemVenda = new ControllerItemVenda();

        int novaQtdItens;

        try {
            
            novaQtdItens = Integer.parseInt(jtfQuantidadeItem.getText());
            itemEditando.setQuantidadeItens(novaQtdItens);

            controllerItemVenda = new ControllerItemVenda();
            controllerItemVenda.editar(itemEditando, jtItensVenda, venda, listaCompras, jtfPrecoTotal, jtProdutos);
            dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na quantidade de itens:\n"+e);
        }


    }//GEN-LAST:event_jbUpdateItemActionPerformed

    private void jbCancelAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelAddItemActionPerformed

        dispose();

    }//GEN-LAST:event_jbCancelAddItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCancelAddItem;
    private javax.swing.JButton jbUpdateItem;
    private javax.swing.JTextField jtfIdItem;
    private javax.swing.JTextField jtfQuantidadeItem;
    // End of variables declaration//GEN-END:variables

}
